title: Documentación
author: Luis Alfonso Olivares Jiménez
email: alfonso.cucei.udg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Uso de Jupyter para el uso de Dosepy
# social links
twitter_username: FMLuisOlivaresJ # DO NOT include the @ character, or else the build will fail!
github_username:  LuisOlivaresJ # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: just-the-docs
plugins:
  - jekyll-seo-tag
url: "https://luisolivaresj.github.io/Dosepy/"
logo: "/assets/images/Logo_Dosepy.png"

# Aux links for the upper right navigation
aux_links:
  "Dosepy on GitHub":
    - "https://github.com/LuisOlivaresJ/Dosepy"
  "Dosepy Home":
    - "https://luisolivaresj.github.io/Dosepy/"

# Footer content
# appears at the bottom of every page's main content

footer_content: "Derechos Reservados (c) Luis Alfonso Olivares Jimenez 2021. Distributed by an <a href=\"https://github.com/LuisOlivaresJ/Dosepy/blob/c8b626036d92e1e16608be0f91695aea2c0a6d36/LICENSE\">PROPRIETARY LICENSE.</a> 03-2021-093012460400-01"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme supports "light" (default) and "dark"
#color_scheme: dark